// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3kpE-8gslNdXnXizbkSM3z1mDi-ngb28',
    appId: '1:302601020872:web:43db1d49b27ec27babccfd',
    messagingSenderId: '302601020872',
    projectId: 'chatai-fc003',
    authDomain: 'chatai-fc003.firebaseapp.com',
    storageBucket: 'chatai-fc003.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHDDIqttvQTWKB-0viPq0_zZVWnzjZPjI',
    appId: '1:302601020872:android:99e16deb3a557752abccfd',
    messagingSenderId: '302601020872',
    projectId: 'chatai-fc003',
    storageBucket: 'chatai-fc003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk21QuEq-uad6uJD7PT25mI5sHfTgB0e4',
    appId: '1:302601020872:ios:a55a45d2e94131adabccfd',
    messagingSenderId: '302601020872',
    projectId: 'chatai-fc003',
    storageBucket: 'chatai-fc003.appspot.com',
    iosClientId: '302601020872-h87nhvkfn36e7990gn0i7he31omee5de.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk21QuEq-uad6uJD7PT25mI5sHfTgB0e4',
    appId: '1:302601020872:ios:a55a45d2e94131adabccfd',
    messagingSenderId: '302601020872',
    projectId: 'chatai-fc003',
    storageBucket: 'chatai-fc003.appspot.com',
    iosClientId: '302601020872-h87nhvkfn36e7990gn0i7he31omee5de.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAi',
  );
}
